### ISSUE TITLE
[FEAT] 지금 우리 학교는? 컴포넌트 개발

### ISSUE THREAD

**Issue by yr0118kim** [TW00D/Letsgo-web-mini#12]
## 어떤 기능입니까?
학교에 대한 "대신 전해드립니다" , "대슐랭가이드(급식 알리미)"를 보여주는 컴포넌트

## TODO
- [x] 대신 전해드립니다 view 개발
- [x] 대슐랭 가이드 view 개발
- [x] #15
- [x] 지금 우리 학교는? 컴포넌트 로직 개발

## 데드라인
2024/03/19 22:00 ~ 2024/03/22 23:59

## 기타 사항
내용 없음
